/*
 * generated by Xtext, then owned here: the block rules are the project language's, not the generator's.
 */
package dev.jorisjonkers.deploykit.emf.syntax.parser.antlr;

import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokenSource;
import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokens;
import dev.jorisjonkers.deploykit.emf.syntax.parser.antlr.internal.InternalClusterStateParser;
import org.antlr.runtime.TokenSource;

public class ClusterStateTokenSource extends BlockTokenSource {

    /** The same block tokens as the project language's, as this language's generated parser numbers them. */
    public static final BlockTokens TYPES = new BlockTokens(
            InternalClusterStateParser.RULE_BEGIN,
            InternalClusterStateParser.RULE_END,
            InternalClusterStateParser.RULE_WS,
            InternalClusterStateParser.RULE_SL_COMMENT,
            InternalClusterStateParser.RULE_DASH,
            InternalClusterStateParser.RULE_FLOW_BEGIN,
            InternalClusterStateParser.RULE_FLOW_END,
            InternalClusterStateParser.RULE_LIST_BEGIN,
            InternalClusterStateParser.RULE_LIST_END,
            InternalClusterStateParser.RULE_FLOW_SEP,
            InternalClusterStateParser.RULE_FOLD,
            InternalClusterStateParser.RULE_SCALAR);

    public ClusterStateTokenSource(TokenSource delegate) {
        super(delegate, TYPES);
    }
}
