/*
 * generated by Xtext, then owned here: the block rules are the project language's, not the generator's.
 */
package dev.jorisjonkers.deploykit.emf.syntax.parser.antlr;

import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokenSource;
import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokens;
import dev.jorisjonkers.deploykit.emf.syntax.parser.antlr.internal.InternalImagesLockParser;
import org.antlr.runtime.TokenSource;

public class ImagesLockTokenSource extends BlockTokenSource {

    /** The same block tokens as the project language's, as this language's generated parser numbers them. */
    public static final BlockTokens TYPES = new BlockTokens(
            InternalImagesLockParser.RULE_BEGIN,
            InternalImagesLockParser.RULE_END,
            InternalImagesLockParser.RULE_WS,
            InternalImagesLockParser.RULE_SL_COMMENT,
            InternalImagesLockParser.RULE_DASH,
            InternalImagesLockParser.RULE_FLOW_BEGIN,
            InternalImagesLockParser.RULE_FLOW_END,
            InternalImagesLockParser.RULE_LIST_BEGIN,
            InternalImagesLockParser.RULE_LIST_END,
            InternalImagesLockParser.RULE_FLOW_SEP,
            InternalImagesLockParser.RULE_FOLD,
            InternalImagesLockParser.RULE_SCALAR);

    public ImagesLockTokenSource(TokenSource delegate) {
        super(delegate, TYPES);
    }
}
