/*
 * generated by Xtext, then owned here: the block rules are the project language's, not the generator's.
 */
package dev.jorisjonkers.deploykit.emf.syntax.parser.antlr;

import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokenSource;
import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokens;
import dev.jorisjonkers.deploykit.emf.syntax.parser.antlr.internal.InternalMigrationProofParser;
import org.antlr.runtime.TokenSource;

public class MigrationProofTokenSource extends BlockTokenSource {

    /** The same block tokens as the project language's, as this language's generated parser numbers them. */
    public static final BlockTokens TYPES = new BlockTokens(
            InternalMigrationProofParser.RULE_BEGIN,
            InternalMigrationProofParser.RULE_END,
            InternalMigrationProofParser.RULE_WS,
            InternalMigrationProofParser.RULE_SL_COMMENT,
            InternalMigrationProofParser.RULE_DASH,
            InternalMigrationProofParser.RULE_FLOW_BEGIN,
            InternalMigrationProofParser.RULE_FLOW_END,
            InternalMigrationProofParser.RULE_LIST_BEGIN,
            InternalMigrationProofParser.RULE_LIST_END,
            InternalMigrationProofParser.RULE_FLOW_SEP,
            InternalMigrationProofParser.RULE_FOLD,
            InternalMigrationProofParser.RULE_SCALAR);

    public MigrationProofTokenSource(TokenSource delegate) {
        super(delegate, TYPES);
    }
}
