/*
 * generated by Xtext, then owned here: the block rules are the project language's, not the generator's.
 */
package dev.jorisjonkers.deploykit.emf.syntax.parser.antlr;

import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokenSource;
import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokens;
import dev.jorisjonkers.deploykit.emf.syntax.parser.antlr.internal.InternalNodeContractParser;
import org.antlr.runtime.TokenSource;

public class NodeContractTokenSource extends BlockTokenSource {

    /** The same block tokens as the project language's, as this language's generated parser numbers them. */
    public static final BlockTokens TYPES = new BlockTokens(
            InternalNodeContractParser.RULE_BEGIN,
            InternalNodeContractParser.RULE_END,
            InternalNodeContractParser.RULE_WS,
            InternalNodeContractParser.RULE_SL_COMMENT,
            InternalNodeContractParser.RULE_DASH,
            InternalNodeContractParser.RULE_FLOW_BEGIN,
            InternalNodeContractParser.RULE_FLOW_END,
            InternalNodeContractParser.RULE_LIST_BEGIN,
            InternalNodeContractParser.RULE_LIST_END,
            InternalNodeContractParser.RULE_FLOW_SEP,
            InternalNodeContractParser.RULE_FOLD,
            InternalNodeContractParser.RULE_SCALAR);

    public NodeContractTokenSource(TokenSource delegate) {
        super(delegate, TYPES);
    }
}
