// The shape of every refusal, and the closed set of codes one may carry: the
// specification's `E_` codes, each defined by the chapter whose rule it
// enforces, and `schema` for a document the reader refuses before any rule
// runs (spec/v1/10-project-intent.md#reading-a-file). `npm run lint:codes`
// holds this list to the chapters, so a code no chapter defines fails the
// typecheck, and a code a chapter defines and this list lacks fails the gate.

/** Every code a refusal may carry. */
export type RefusalCode =
  | "schema"
  | "E_ALERT_CLASS_WITHOUT_SIGNAL"
  | "E_AMBIENT_INPUT_FORBIDDEN"
  | "E_CHANGELOG_MISSING"
  | "E_CONTRACT_TOO_EARLY"
  | "E_CREDENTIALS_WITHOUT_DATABASE"
  | "E_CUTOVER_MISSING"
  | "E_CUTOVER_UNHONOURABLE"
  | "E_DEPENDENCY_CYCLE"
  | "E_DISK_BINDING_CONFLICT"
  | "E_DUPLICATE_APEX"
  | "E_DUPLICATE_APPLICATION_ID"
  | "E_DUPLICATE_EXPOSURE_NAME"
  | "E_DUPLICATE_HOST"
  | "E_DUPLICATE_PROCESS_NAME"
  | "E_DUPLICATE_PROJECT"
  | "E_DUPLICATE_ROUTE"
  | "E_DUPLICATE_ROUTE_MATCH"
  | "E_DURABILITY_WITHOUT_ENGINE"
  | "E_ENGINE_WITHOUT_DURABILITY"
  | "E_ENV_CANNOT_RELOAD"
  | "E_FLOATING_IMAGE"
  | "E_FORBIDDEN_KIND"
  | "E_FOREIGN_NAMESPACE"
  | "E_HANDOVER_BOTH_PATHS"
  | "E_HANDOVER_UNLISTED"
  | "E_HARDENING_UNMET"
  | "E_ILLEGAL_DELIVERY_FOR_ACCESS"
  | "E_IMAGE_LOCK_CONFLICT"
  | "E_IMAGE_USER_NOT_NUMERIC"
  | "E_INPUT_OUTSIDE_WORKDIR"
  | "E_LEDGER_ENTRY_STALE"
  | "E_LEDGER_REVIEW_OVERDUE"
  | "E_MIGRATION_OWNER_DUPLICATED"
  | "E_MIGRATION_UNDECLARED"
  | "E_MIGRATION_UNGATED"
  | "E_MIGRATION_WITHOUT_DATABASE"
  | "E_NODE_CONTRACT_MISMATCH"
  | "E_NON_KV_DELIVERY"
  | "E_NO_DELIVERY_POLICY"
  | "E_NO_DURABILITY_POLICY"
  | "E_NO_ENGINE_POLICY"
  | "E_BACKUP_SURFACE_NOT_PROVIDED"
  | "E_NO_FORWARD_AUTH_ENDPOINT"
  | "E_NO_MIGRATION_POLICY"
  | "E_NO_TIER_FOR_AUDIENCE"
  | "E_OWNER_ROLE_GRANTED"
  | "E_PARTICIPANT_MISSING"
  | "E_PARTICIPANT_STALE"
  | "E_PARTICIPANT_UNLISTED"
  | "E_PATH_COLLISION"
  | "E_PLACEMENT_INCOMPLETE"
  | "E_PLACEMENT_UNSATISFIABLE"
  | "E_PREPARE_PROCESS_SERVES"
  | "E_PRIVILEGED_PORT_UNDER_NONROOT"
  | "E_PROCESS_RBAC_GRANT"
  | "E_PROVIDER_WITHOUT_COORDINATES"
  | "E_RAW_SECRET"
  | "E_READER_NOT_DECLARED"
  | "E_RELEASE_UNIT_MIXED_CUTOVER"
  | "E_RELEASE_UNIT_NO_READINESS"
  | "E_RELEASE_UNIT_SINGLETON"
  | "E_RENDER_NONDETERMINISTIC"
  | "E_RENDER_OVERWRITE_REFUSED"
  | "E_ROLL_AFFECTS_OTHER_READERS"
  | "E_ROUTE_AUTH_MODE_NOT_IN_TIER"
  | "E_SCHEMA_VERSION_MISMATCH"
  | "E_SECRETS_AT_REST_REQUIRED"
  | "E_SHARED_DECLARATION_DUPLICATED"
  | "E_SHARED_QUANTITY"
  | "E_STORAGE_UNSATISFIABLE"
  | "E_SUBTREE_PREFIX_COLLISION"
  | "E_UNACCEPTED_DRIFT"
  | "E_UNATTRIBUTED_OBJECT"
  | "E_UNAUTHORISED_SECRET_REFERENCE"
  | "E_UNBOUND_SECRET_GRANT"
  | "E_UNDECLARED_SECRET_PATH"
  | "E_UNKNOWN_API_HOLDER"
  | "E_UNKNOWN_ENV_SCOPE"
  | "E_UNKNOWN_MACHINERY"
  | "E_UNKNOWN_METRICS_STACK"
  | "E_UNKNOWN_OVERRIDE"
  | "E_UNKNOWN_PROCESS"
  | "E_UNKNOWN_RELEASE_GATE"
  | "E_UNKNOWN_SECRET_STORE"
  | "E_UNKNOWN_SURFACE"
  | "E_UNKNOWN_TELEMETRY_COLLECTOR"
  | "E_UNKNOWN_TIER_PROXY"
  | "E_UNLOCKED_IMAGE"
  | "E_UNMANAGED_SURFACE_WITHOUT_COORDINATES"
  | "E_UNREGISTERED_SURFACE"
  | "E_UNRESOLVED_APPLICATION"
  | "E_UNSAFE_OUTPUT_PATH";

export interface Diagnostic {
  readonly code: RefusalCode;
  /** The authored file the path points into, where more than one is read together. */
  readonly document?: string;
  readonly path: string;
  readonly message: string;
  readonly hint: string;
}

export type Result<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly diagnostics: readonly Diagnostic[] };
