/*
 * generated by Xtext
 */
package dev.jorisjonkers.deploykit.emf.syntax;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProjectIntentRuntimeModule extends AbstractProjectIntentRuntimeModule {}
