/*
 * generated by Xtext
 */
package dev.jorisjonkers.deploykit.emf.syntax;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProjectIntentStandaloneSetup extends ProjectIntentStandaloneSetupGenerated {

    public static void doSetup() {
        new ProjectIntentStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
