/*
 * generated by Xtext, then owned here: the value converters are this language's.
 */
package dev.jorisjonkers.deploykit.emf.syntax;

import dev.jorisjonkers.deploykit.emf.syntax.values.ProjectIntentValueConverters;
import org.eclipse.xtext.conversion.IValueConverterService;

/** Registers the components this language runs with, outside the Eclipse extension registry. */
public class ProjectIntentRuntimeModule extends AbstractProjectIntentRuntimeModule {

    /** Quotes are syntax and a boolean is a boolean: see {@link ProjectIntentValueConverters}. */
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return ProjectIntentValueConverters.class;
    }
}
