/*
 * generated by Xtext
 */
package dev.jorisjonkers.deploykit.emf.syntax;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ClusterStateStandaloneSetup extends ClusterStateStandaloneSetupGenerated {

    public static void doSetup() {
        new ClusterStateStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
