/*
 * generated by Xtext, then owned here: the value converters are the project language's.
 */
package dev.jorisjonkers.deploykit.emf.syntax;

import dev.jorisjonkers.deploykit.emf.syntax.values.ProjectIntentValueConverters;
import org.eclipse.xtext.conversion.IValueConverterService;

/** Registers the components the ClusterState snapshot language runs with: the project language's own, reused. */
public class ClusterStateRuntimeModule extends AbstractClusterStateRuntimeModule {

    /** Quotes are syntax: see {@link ProjectIntentValueConverters}. */
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return ProjectIntentValueConverters.class;
    }
}
