/*
 * generated by Xtext
 */
package dev.jorisjonkers.deploykit.emf.syntax;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ImagesLockStandaloneSetup extends ImagesLockStandaloneSetupGenerated {

    public static void doSetup() {
        new ImagesLockStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
