/*
 * generated by Xtext
 */
package dev.jorisjonkers.deploykit.emf.syntax;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MigrationProofStandaloneSetup extends MigrationProofStandaloneSetupGenerated {

    public static void doSetup() {
        new MigrationProofStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
