/*
 * generated by Xtext
 */
package dev.jorisjonkers.deploykit.emf.syntax;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NodeContractStandaloneSetup extends NodeContractStandaloneSetupGenerated {

    public static void doSetup() {
        new NodeContractStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
