/*
 * generated by Xtext, then owned here: the value converters are the project language's.
 */
package dev.jorisjonkers.deploykit.emf.syntax;

import dev.jorisjonkers.deploykit.emf.syntax.values.ProjectIntentValueConverters;
import org.eclipse.xtext.conversion.IValueConverterService;

/** Registers the components the node contract language runs with: the project language's own, reused. */
public class NodeContractRuntimeModule extends AbstractNodeContractRuntimeModule {

    /** Quotes are syntax: see {@link ProjectIntentValueConverters}. */
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return ProjectIntentValueConverters.class;
    }
}
