/*
 * generated by Xtext
 */
package dev.jorisjonkers.deploykit.emf.syntax;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PlatformIntentStandaloneSetup extends PlatformIntentStandaloneSetupGenerated {

    public static void doSetup() {
        new PlatformIntentStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
