/*
 * generated by Xtext, then owned here: the value converters and the linking are this language's.
 */
package dev.jorisjonkers.deploykit.emf.syntax;

import dev.jorisjonkers.deploykit.emf.syntax.linking.ProjectIntentScopes;
import dev.jorisjonkers.deploykit.emf.syntax.linking.UnlinkedNames;
import dev.jorisjonkers.deploykit.emf.syntax.values.ProjectIntentValueConverters;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

/** Registers the components this language runs with, outside the Eclipse extension registry. */
public class ProjectIntentRuntimeModule extends AbstractProjectIntentRuntimeModule {

    /** Quotes are syntax and a boolean is a boolean: see {@link ProjectIntentValueConverters}. */
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return ProjectIntentValueConverters.class;
    }

    /** A route's and a scrape's names link inside their Application: see {@link ProjectIntentScopes}. */
    @Override
    public Class<? extends IScopeProvider> bindIScopeProvider() {
        return ProjectIntentScopes.class;
    }

    /** A name that links to nothing carries its specification code: see {@link UnlinkedNames}. */
    public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider() {
        return UnlinkedNames.class;
    }
}
