// JSON Schema, generated from the metamodel and committed.
//
// "JSON Schema is generated from the **input** variant of each schema, because
// a field with a platform default is optional in the file a human writes and
// required only after validation"
// (docs/architecture.md#the-wire-boundary). `io: "input"` is that choice, and
// it is why `engine` is optional here and always present in the domain model.
//
// The output is committed to spec/v1/schemas/ and regenerated by the intent
// gate, which fails on a diff. An editor pointed at the committed file and the
// loader's own refusal therefore come from one declaration; when they last came
// from two, one of them was wrong and nothing said which.
import { z } from "zod";
import { METAMODEL, Domain } from "./schema.ts";

/** Where the committed copy lives, relative to the repository root. */
export const JSON_SCHEMA_PATH = "spec/v1/schemas/service-intent.schema.json";

/**
 * The Service Intent JSON Schema: the document at the root, every other class
 * of the metamodel under `$defs`, so a class the document does not reach (an
 * `EnvFile`, a `Placeholder`) is still published and still generated from the
 * same declaration.
 */
export function serviceIntentJsonSchema(): unknown {
  const defs = Object.fromEntries(
    Object.entries(METAMODEL.classes)
      .filter(([name]) => name !== METAMODEL.document)
      .map(([name, schema]) => [name, z.toJSONSchema(schema, { io: "input" })]),
  );
  return {
    ...(z.toJSONSchema(Domain, { io: "input" }) as Record<string, unknown>),
    title: `${METAMODEL.name}: ${METAMODEL.document}`,
    $defs: defs,
  };
}

/** The committed bytes: pretty-printed, newline-terminated, stable key order. */
export function serviceIntentJsonSchemaText(): string {
  return `${JSON.stringify(serviceIntentJsonSchema(), null, 2)}\n`;
}
