/*
 * generated by Xtext, then owned here: the block rules are the project language's, not the generator's.
 */
package dev.jorisjonkers.deploykit.emf.syntax.parser.antlr;

import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokenSource;
import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokens;
import dev.jorisjonkers.deploykit.emf.syntax.parser.antlr.internal.InternalPlatformIntentParser;
import org.antlr.runtime.TokenSource;

public class PlatformIntentTokenSource extends BlockTokenSource {

    /** The same block tokens as the project language's, as this language's generated parser numbers them. */
    public static final BlockTokens TYPES = new BlockTokens(
            InternalPlatformIntentParser.RULE_BEGIN,
            InternalPlatformIntentParser.RULE_END,
            InternalPlatformIntentParser.RULE_WS,
            InternalPlatformIntentParser.RULE_SL_COMMENT,
            InternalPlatformIntentParser.RULE_DASH,
            InternalPlatformIntentParser.RULE_FLOW_BEGIN,
            InternalPlatformIntentParser.RULE_FLOW_END,
            InternalPlatformIntentParser.RULE_LIST_BEGIN,
            InternalPlatformIntentParser.RULE_LIST_END,
            InternalPlatformIntentParser.RULE_FLOW_SEP,
            InternalPlatformIntentParser.RULE_FOLD,
            InternalPlatformIntentParser.RULE_SCALAR);

    public PlatformIntentTokenSource(TokenSource delegate) {
        super(delegate, TYPES);
    }
}
