/*
 * generated by Xtext, then owned here: the block rules are this language's, not the generator's.
 */
package dev.jorisjonkers.deploykit.emf.syntax.parser.antlr;

import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokenSource;
import dev.jorisjonkers.deploykit.emf.syntax.blocks.BlockTokens;
import dev.jorisjonkers.deploykit.emf.syntax.parser.antlr.internal.InternalProjectIntentParser;
import org.antlr.runtime.TokenSource;

public class ProjectIntentTokenSource extends BlockTokenSource {

    public static final BlockTokens TYPES = new BlockTokens(
            InternalProjectIntentParser.RULE_BEGIN,
            InternalProjectIntentParser.RULE_END,
            InternalProjectIntentParser.RULE_WS,
            InternalProjectIntentParser.RULE_SL_COMMENT,
            InternalProjectIntentParser.RULE_DASH,
            InternalProjectIntentParser.RULE_FLOW_BEGIN,
            InternalProjectIntentParser.RULE_FLOW_END,
            InternalProjectIntentParser.RULE_LIST_BEGIN,
            InternalProjectIntentParser.RULE_LIST_END,
            InternalProjectIntentParser.RULE_FLOW_SEP);

    public ProjectIntentTokenSource(TokenSource delegate) {
        super(delegate, TYPES);
    }
}
